//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarLoans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplications
    {
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string AmountOfCredit { get; set; }
        public string TCPNumber { get; set; }
        public string Income { get; set; }
        public string FIO { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Car { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Clients Clients { get; set; }
    }
}
